In [3]:
import torch

In [4]:
A = torch.arange(40, dtype =torch.float64).reshape(2,5,4)
A

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]],

        [[20., 21., 22., 23.],
         [24., 25., 26., 27.],
         [28., 29., 30., 31.],
         [32., 33., 34., 35.],
         [36., 37., 38., 39.]]], dtype=torch.float64)

In [5]:
A.sum(axis = 0), A.sum(axis=1), A.sum(axis=[0,1])

(tensor([[20., 22., 24., 26.],
         [28., 30., 32., 34.],
         [36., 38., 40., 42.],
         [44., 46., 48., 50.],
         [52., 54., 56., 58.]], dtype=torch.float64),
 tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]], dtype=torch.float64),
 tensor([180., 190., 200., 210.], dtype=torch.float64))

In [6]:
A.mean(), A.mean(axis=0)

(tensor(19.5000, dtype=torch.float64),
 tensor([[10., 11., 12., 13.],
         [14., 15., 16., 17.],
         [18., 19., 20., 21.],
         [22., 23., 24., 25.],
         [26., 27., 28., 29.]], dtype=torch.float64))

In [7]:
A.sum(axis=1), A.sum(axis=1, keepdims=True)

(tensor([[ 40.,  45.,  50.,  55.],
         [140., 145., 150., 155.]], dtype=torch.float64),
 tensor([[[ 40.,  45.,  50.,  55.]],
 
         [[140., 145., 150., 155.]]], dtype=torch.float64))

In [8]:
A,A.cumsum(axis=0)

(tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]], dtype=torch.float64),
 tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 22., 24., 26.],
          [28., 30., 32., 34.],
          [36., 38., 40., 42.],
          [44., 46., 48., 50.],
          [52., 54., 56., 58.]]], dtype=torch.float64))

In [9]:
x = torch.arange(4, dtype=torch.float32)
y = torch.ones(4, dtype=torch.float32)

x, y, torch.dot(x,y), torch.sum(x*y), x.dot(y) == y.dot(x)

(tensor([0., 1., 2., 3.]),
 tensor([1., 1., 1., 1.]),
 tensor(6.),
 tensor(6.),
 tensor(True))

In [10]:
A = torch.arange(20, dtype = torch.float32).reshape((5,4))
B = torch.ones(4,3)

torch.mm(A, B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [11]:
# L2 norm
u = torch.tensor([3.0, -4.0])
torch.norm(u)

tensor(5.)

In [12]:
# L1 norm
torch.abs(u).sum()

tensor(7.)

In [13]:
# Frobenius norm
torch.norm(torch.ones((4,9)))

tensor(6.)

In [20]:
x = torch.arange(4, dtype=torch.float32, requires_grad=True)
y = 2*torch.dot(x,x)

x, x.grad, y

(tensor([0., 1., 2., 3.], requires_grad=True),
 None,
 tensor(28., grad_fn=<MulBackward0>))

In [ ]:
# Backpropagation
y.backward(retain_graph=True)

x.grad

tensor([ 0.,  4.,  8., 12.])

In [ ]:
# Initializing gradients to zero
x.grad.zero_()
y = x.sum()
y.backward()

# The gradient is accumulated without initialization
x.grad

tensor([1., 1., 1., 1.])

In [ ]:
x.grad.zero_()

# If y is a matrix, we can use the sum function to get a scalar
y = x * x
y.sum().backward()

x.grad

tensor([0., 2., 4., 6.])

In [ ]:
x.grad.zero_()

y = x * x

# Detach the tensor from the computational graph
# This will not track gradients
u = y.detach()
z = u * x  # This can be treated as a constant multiplied by x

z.sum().backward()
x, x.grad

(tensor([0., 1., 2., 3.], requires_grad=True), tensor([0., 1., 4., 9.]))

In [56]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

# Size is () means a scalar
a = torch.randn(size=(), requires_grad=True)
d = f(a)
d.backward()

a.grad, d, d/a

(tensor(1024.),
 tensor(1348.1610, grad_fn=<MulBackward0>),
 tensor(1024., grad_fn=<DivBackward0>))